# Generated by Django 5.2.14 on 2026-05-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('from_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='scale_app.process')),
                ('to_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='scale_app.process')),
            ],
        ),
        migrations.CreateModel(
            name='EmergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('transformity', models.FloatField(help_text='sej por unidade (ex: sej/MJ, sej/kg)')),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergy_sources', to='scale_app.process')),
            ],
        ),
    ]
