# Generated by Django 5.2.14 on 2026-05-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emergysource',
            name='category',
            field=models.CharField(choices=[('R', 'Renovável'), ('N', 'Não Renovável'), ('M', 'Materiais'), ('U', 'Não Classificado')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='emergysource',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='scale_app.inventory'),
        ),
        migrations.AddField(
            model_name='flow',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='scale_app.inventory'),
        ),
        migrations.AddField(
            model_name='process',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='scale_app.inventory'),
        ),
    ]
